name: CI

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://docs.runx.dev/install.sh)"
          opta version
